### ISSUE TITLE
Why is this written in node, how is it supposed to run in a browser?

### ISSUE THREAD

**Issue by skeddles** [riebel/pixi-tiledmap#10]

**Comment by riebel** [comment]
Have a look at the example/browser/index.html (needs to run on a webserver, if you want to try it out yourself)
Or check it out here: [http://theriebel.de/pixi-tiledmap/example/browser/](http://theriebel.de/pixi-tiledmap/example/browser/)

**Comment by skeddles** [comment]
Now I'm more confused because if I run the example it works fine (without a server), but if I change the map file I get TypeError: E.readFile is not a function

**Comment by riebel** [comment]
Maybe #7 will resolve your issue? Did you copy your images to the same folder?

**Comment by skeddles** [comment]
Thanks, what actually did it was setting the maps tile layer format to base64/zlib.

BTW, does this import the tile 'type' property or custom properties anywhere?
