### ISSUE TITLE
Attempts to use fs (from node) while in browser. Am I missing a step?

### ISSUE THREAD

**Issue by timetocode** [riebel/pixi-tiledmap#2]
I get the following error when attempting to load a tmx file:

pixi-tiledmap.js:12529 Uncaught TypeError: fs.readFile is not a function
    at Object.defaultReadFile [as readFile] (pixi-tiledmap.js:12529)
    at parseFile (pixi-tiledmap.js:12533)
    at resolveTileSet (pixi-tiledmap.js:12480)
    at pixi-tiledmap.js:12437
    at pendGo (pixi-tiledmap.js:12752)
    at Pend.go (pixi-tiledmap.js:12711)
    at collectTileSet (pixi-tiledmap.js:12436)
    at Object.opentag (pixi-tiledmap.js:11947)
    at SAXParser.parser.onopentag (pixi-tiledmap.js:12372)
    at emit (pixi-tiledmap.js:13381)

I get similar errors with using the min version, and when using require + browerify or webpack.

My source code looks lilke:

    PIXI.loader.add('/images/spritesheet.png', '/images/spritesheet.json')
    PIXI.loader.add('mountain.tmx')
    PIXI.loader.load(function(loader, resource) {
        var tileMap = new PIXI.extras.TiledMap('mountain.tmx')
        ...

Thanks!

**Comment by riebel** [comment]
did you try

`node: {
  fs: 'empty'
}`

in your webpack config?

Nonetheless this project needs to be updated soon :)

**Comment by riebel** [comment]
> Nonetheless this project needs to be updated soon :)

and done.

It should work now with the recent versions of pixi.js and webpack.

And remember to use `node: { fs: 'empty' }` in your webpack config.

**Comment by riebel** [comment]
I also added a working example with webpack under example/ in 1.8.1

**Comment by timetocode** [comment]
It is now working for me using 1.8.1, node: { fs: 'empty' }, and embedding the spritesheet when creating a map (PIXI v4.3.4 and Tiled v1.0.2).
Thanks for your help!
