### ISSUE TITLE
I use Gulp+Browserify, how do I configure the config, so that there is no error ` fs.readFile is not a function`

### ISSUE THREAD

**Issue by azbang** [riebel/pixi-tiledmap#3]
Hello! In the example, you can find the working config for webpack using `node: {fs: 'empty'}`, but what if I do not use webpack? I also thought that the `pixi-tiledmap.min.js` connected in html already has a solution to the problem, but the same error occurs.

**Comment by riebel** [comment]
Maybe you can use:

[https://github.com/browserify/brfs](https://github.com/browserify/brfs)

or 

[https://github.com/mafintosh/browserify-fs](https://github.com/mafintosh/browserify-fs )

here is a [stackoverflow post](https://stackoverflow.com/questions/16640177/browserify-with-requirefs) worth checking out.

**Comment by azbang** [comment]
Yes, there is a solution.
However, as far as I understand, "node-tmx-parser" uses node fs only to read the tmx file. Why not make a fork of this library that does not have a fs module? I believe that this can help in solving the root of the problem.

**Comment by riebel** [comment]
I completely refactored the code and `pixi-tiledmap.min.js` should now behave as expected in v1.9.2 (i hope ;)).

**Comment by azbang** [comment]
👍
