### ISSUE TITLE
webpack fails because of src/Tileset.js case

### ISSUE THREAD

**Issue by lthms** [riebel/pixi-tiledmap#5]
The file [src/Tileset.js](https://github.com/riebel/pixi-tiledmap/blob/master/src/Tileset.js) is required in [src/TileMap.js](https://github.com/riebel/pixi-tiledmap/blob/master/src/TiledMap.js) using an incorrect case, [as fas as I can tell](https://github.com/riebel/pixi-tiledmap/blob/master/src/TiledMap.js#L1).

This makes webpack to fail, because it cannot find the package. Maybe newer version of webpack are case sensitive? I admit I have no idea.

Renaming the file in my `node_modules` directory is a quick and dirty solution which works.

**Comment by riebel** [comment]
Thanks for your input! The camel case got messed up in the last update. Should be fine now.

**Comment by lthms** [comment]
Yes it is! Thanks a lot for the quick reaction, it works like a charm now.
