### ISSUE TITLE
Tile events docs

### ISSUE THREAD

**Issue by DavidGOrtega** [riebel/pixi-tiledmap#6]
Hi,

I was looking for a sprite map editor for PIXI when I found this! 
I have been looking at the docs but I can't see how to set tile events like click. I guess that I will have to do it accessing the children... is there any example?

**Comment by riebel** [comment]
Each tile is an instance of PIXI.extras.AnimatedSprite, so you can handle interaction with the `interactive` flag.

e.g.:
```
// get a tile
let tile = myMap.children[2].tiles[4];

tile.interactive = true;
tile.on('tap', (event) => {
   //handle event
});
```
see [http://pixijs.download/dev/docs/PIXI.extras.AnimatedSprite.html#interactive](http://pixijs.download/dev/docs/PIXI.extras.AnimatedSprite.html#interactive)

**Comment by DavidGOrtega** [comment]
brilliant! Thanks!
